// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vanilla.Infrastructure.Data;

#nullable disable

namespace Vanilla.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6").HasAnnotation("Relational:MaxIdentifierLength", 128);
            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vanilla.Domain.Customer", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<string>("DeletedReason").HasMaxLength(250).HasColumnType("nvarchar(250)");
                b.Property<DateTime?>("DeletedUtc").HasColumnType("datetime2");
                b.Property<string>("Email").HasColumnType("nvarchar(max)");
                b.Property<bool>("IsDeleted").ValueGeneratedOnAdd().HasColumnType("bit").HasDefaultValue(false);
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Notes").HasColumnType("nvarchar(max)");
                b.Property<string>("Phone").HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.HasIndex("IsDeleted", "Name");
                b.ToTable("Customers", (string)null);
            });

            modelBuilder.Entity("Vanilla.Domain.Order", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<decimal>("Amount").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.Property<DateTime>("CreatedUtc").HasColumnType("datetime2");
                b.Property<Guid>("CustomerId").HasColumnType("uniqueidentifier");
                b.Property<string>("DeletedReason").HasMaxLength(250).HasColumnType("nvarchar(250)");
                b.Property<DateTime?>("DeletedUtc").HasColumnType("datetime2");
                b.Property<bool>("IsDeleted").ValueGeneratedOnAdd().HasColumnType("bit").HasDefaultValue(false);
                b.Property<string>("Notes").HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.HasIndex("CustomerId", "IsDeleted", "CreatedUtc");
                b.ToTable("Orders", (string)null);
            });

            modelBuilder.Entity("Vanilla.Domain.Payment", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<decimal>("Amount").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.Property<DateTime>("CreatedUtc").HasColumnType("datetime2");
                b.Property<Guid>("CustomerId").HasColumnType("uniqueidentifier");
                b.Property<string>("DeletedReason").HasMaxLength(250).HasColumnType("nvarchar(250)");
                b.Property<DateTime?>("DeletedUtc").HasColumnType("datetime2");
                b.Property<bool>("IsDeleted").ValueGeneratedOnAdd().HasColumnType("bit").HasDefaultValue(false);
                b.Property<string>("Notes").HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.HasIndex("CustomerId", "IsDeleted", "CreatedUtc");
                b.ToTable("Payments", (string)null);
            });

            modelBuilder.Entity("Vanilla.Domain.Order", b =>
            {
                b.HasOne("Vanilla.Domain.Customer", "Customer").WithMany("Orders").HasForeignKey("CustomerId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.Navigation("Customer");
            });

            modelBuilder.Entity("Vanilla.Domain.Payment", b =>
            {
                b.HasOne("Vanilla.Domain.Customer", "Customer").WithMany("Payments").HasForeignKey("CustomerId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.Navigation("Customer");
            });

            modelBuilder.Entity("Vanilla.Domain.Customer", b =>
            {
                b.Navigation("Orders");
                b.Navigation("Payments");
            });
#pragma warning restore 612, 618
        }
    }
}